experiment:
  name: gpu_test_lstm_fedavg
  seed: 42
federated:
  architecture: flat
  num_clients: 2
  num_rounds_global: 3
  proximal_mu: 0.1
  proximal_mu_adaptive: true
  strategy: fedavg
input_dim: 78
model_type: lstm
network:
  global_server:
    ip: 127.0.0.1
    port: 29002
num_classes: 2
training:
  batch_size: 256
  epochs: 1
  lr: 0.001
  optimizer: adam
