experiment:
  name: mlp_fedavg_30
  seed: 42
federated:
  architecture: flat
  num_clients: 9
  num_rounds_global: 30
  strategy: fedprox
input_dim: 78
model_type: mlp
network:
  global_server:
    ip: 127.0.0.1
    port: 8080
num_classes: 2
training:
  batch_size: 256
  epochs: 3
  lr: 0.001
  optimizer: adam
