experiment:
  name: simple_test
  seed: 42
federated:
  architecture: flat
  num_clients: 2
  num_rounds_global: 3
  strategy: fedavg
input_dim: 78
model_type: mlp
network:
  global_server:
    ip: 127.0.0.1
    port: 27565
num_classes: 2
training:
  batch_size: 256
  epochs: 1
  lr: 0.001
  optimizer: adam
